# Generated by Django 2.2.7 on 2020-02-27 19:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envios', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaHD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hd', models.CharField(max_length=50, verbose_name='Hard Disk')),
            ],
            options={
                'verbose_name': 'HD',
                'verbose_name_plural': 'HDs',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaMemoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoria', models.CharField(max_length=50, verbose_name='Memória')),
            ],
            options={
                'verbose_name': 'Memoria',
                'verbose_name_plural': 'Memorias',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProcessador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processador', models.CharField(max_length=50, verbose_name='Processador')),
            ],
            options={
                'verbose_name': 'Processador',
                'verbose_name_plural': 'Processadores',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaSO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so', models.CharField(max_length=50, verbose_name='Sistema Operacional')),
            ],
            options={
                'verbose_name': 'SO',
                'verbose_name_plural': 'SOs',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('serial', models.CharField(max_length=100, verbose_name='Serial')),
                ('patrimonio', models.CharField(max_length=100, verbose_name='Patrimônio')),
                ('backup', models.BooleanField(default=False, verbose_name='Backup?')),
                ('setor', models.CharField(choices=[('FRENTE CAIXA', 'Frente de caixa'), ('RECEPCAO', 'Recepção'), ('SALAO', 'Salao'), ('PERECIVEIS', 'Perecíveis'), ('GERENCIA', 'Gerência'), ('TESOURARIA', 'Tesouraria'), ('SEGURANCA', 'Segurança'), ('RM', 'Rm'), ('RM FISCAL', 'Rm Fiscal'), ('CONTABILIDADE', 'Contabilidade'), ('RH', 'Rh'), ('ACOUGUE', 'Açougue'), ('TREINAMENTO', 'Treinamento'), ('SOE', 'Soe'), ('ALMOXARIFADO', 'Almoxarifado'), ('CPD', 'CPD'), ('CALLCENTER', 'Callcenter'), ('COMERCIAL', 'Comercial'), ('PRECIFICACAO', 'Precificação'), ('PADARIA', 'Padaria'), ('MANUTENCAO', 'Manutenção'), ('HORTIFRUTI', 'Hortifruti'), ('CREDITO', 'Crédito'), ('ENCARREGADOS', 'Encarregados'), ('ALMOXARIFADO', 'Almoxarifado'), ('RESTAURANTE', 'Restaurante'), ('SND', 'SND'), ('GERAL', 'Geral'), ('POSTO-PISTA', 'Posto-Pista'), ('POSTO-ADM', 'Posto-Adm'), ('Logistica', 'Logistica')], max_length=50, verbose_name='Setor')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('qtd', models.IntegerField(default=0, verbose_name='Estoque')),
                ('obs', models.TextField()),
                ('hd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.CategoriaHD')),
                ('loja', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Lojas', verbose_name='Loja')),
                ('memoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.CategoriaMemoria')),
                ('processador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.CategoriaProcessador')),
                ('so', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.CategoriaSO')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('defeito', models.CharField(max_length=200, verbose_name='Defeito')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimento', to='envios.EnvioBh')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Equipamento')),
            ],
            options={
                'verbose_name': 'Movimento',
                'verbose_name_plural': 'Movimentos',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
