# Generated by Django 2.2.7 on 2021-12-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20200617_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='obs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='setor',
            field=models.CharField(choices=[('FRENTE CAIXA', 'Frente de caixa'), ('RECEPCAO', 'Recepção'), ('SALAO', 'Salao'), ('PERECIVEIS', 'Perecíveis'), ('GERENCIA', 'Gerência'), ('TESOURARIA', 'Tesouraria'), ('SEGURANCA', 'Segurança'), ('RM', 'Rm'), ('RM FISCAL', 'Rm Fiscal'), ('CONTABILIDADE', 'Contabilidade'), ('RH', 'Rh'), ('ACOUGUE', 'Açougue'), ('TREINAMENTO', 'Treinamento'), ('SOE', 'Soe'), ('CPD', 'CPD'), ('CALLCENTER', 'Callcenter'), ('COMERCIAL', 'Comercial'), ('PRECIFICACAO', 'Precificação'), ('PADARIA', 'Padaria'), ('MANUTENCAO', 'Manutenção'), ('HORTIFRUTI', 'Hortifruti'), ('CREDITO', 'Crédito'), ('ENCARREGADOS', 'Encarregados'), ('ALMOXARIFADO', 'Almoxarifado'), ('RESTAURANTE', 'Restaurante'), ('SND', 'SND'), ('GERAL', 'Geral'), ('POSTO-PISTA', 'Posto-Pista'), ('POSTO-ADM', 'Posto-Adm'), ('LOGISTICA', 'Logistica'), ('EXPEDICAO', 'Expedição'), ('PRESIDENCIA', 'Presidência')], max_length=50, verbose_name='Setor'),
        ),
    ]
