# Generated by Django 2.2.7 on 2020-01-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitoDados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_filial', models.CharField(max_length=20)),
                ('cod_filial', models.IntegerField()),
                ('faixa_ip', models.IntegerField()),
                ('produto', models.CharField(max_length=20)),
                ('circuito', models.CharField(max_length=20)),
                ('roteador', models.CharField(max_length=20)),
                ('velocidade', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CircuitoVoz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao_filial', models.CharField(max_length=20)),
                ('operadora', models.CharField(max_length=20)),
                ('designacao', models.CharField(max_length=50)),
                ('servico_equipamento', models.CharField(max_length=50)),
                ('tel_abrir_chamado', models.IntegerField()),
                ('op_urla', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DataInauguracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_filial', models.IntegerField()),
                ('loja', models.CharField(max_length=20)),
                ('inauguracao', models.CharField(max_length=20)),
            ],
        ),
    ]
