# Generated by Django 2.2.7 on 2020-02-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitoDados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_filial', models.CharField(max_length=20)),
                ('cod_filial', models.CharField(max_length=20, null=True)),
                ('faixa_ip', models.CharField(max_length=20, null=True)),
                ('produto', models.CharField(max_length=20)),
                ('circuito', models.CharField(max_length=20)),
                ('roteador', models.CharField(max_length=20, null=True)),
                ('velocidade', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CircuitoVoz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao_filial', models.CharField(max_length=20)),
                ('operadora', models.CharField(max_length=100)),
                ('designacao', models.CharField(max_length=200)),
                ('servico_equipamento', models.CharField(max_length=200, null=True)),
                ('tel_abrir_chamado', models.CharField(max_length=30, null=True)),
                ('op_urla', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataInauguracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_filial', models.IntegerField()),
                ('loja', models.CharField(max_length=20)),
                ('inauguracao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestDataInauguracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_filial', models.IntegerField()),
                ('loja', models.CharField(max_length=20)),
                ('inauguracao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IpFixo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_interno', models.CharField(max_length=25, verbose_name='Ip interno')),
                ('porta_interna', models.IntegerField(verbose_name='Porta Interna')),
                ('ip_externo', models.CharField(max_length=25, verbose_name='Ip externo')),
                ('porta_externa', models.IntegerField(verbose_name='Porta Ixterna')),
                ('status_online', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], max_length=20, verbose_name='Status do servico')),
                ('filial', models.ForeignKey(on_delete='CASCADE', to='core.Lojas')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoIncidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidente', models.CharField(max_length=400)),
                ('data', models.DateTimeField()),
                ('filial', models.ForeignKey(on_delete='CASCADE', to='core.Lojas')),
            ],
        ),
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.CharField(max_length=50)),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
                ('dias', models.IntegerField()),
                ('decimo_terceiro', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], max_length=20, verbose_name='Decimo Terceiro')),
                ('filial', models.ForeignKey(on_delete='CASCADE', to='core.Lojas')),
            ],
        ),
        migrations.CreateModel(
            name='CentralTelefonica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('end_ip', models.CharField(max_length=20, verbose_name='End. IP')),
                ('qtd_ramais', models.IntegerField(verbose_name='Quantidade de ramais')),
                ('qtd_ramais_utilizados', models.IntegerField(verbose_name='Quantidade de ramais utilizados')),
                ('dt_ult_preventiva', models.DateField(null=True, verbose_name='Data ultima preventiva')),
                ('obs', models.CharField(max_length=400, null=True)),
                ('filial', models.ForeignKey(on_delete='CASCADE', to='core.Lojas')),
            ],
        ),
    ]
