# Generated by Django 2.2.7 on 2021-10-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitovoz',
            name='designacao',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='circuitovoz',
            name='op_urla',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='circuitovoz',
            name='operadora',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='circuitovoz',
            name='regiao_filial',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='circuitovoz',
            name='servico_equipamento',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='circuitovoz',
            name='tel_abrir_chamado',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
