# Generated by Django 2.2.7 on 2020-01-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainauguracao',
            name='inauguracao',
            field=models.IntegerField(),
        ),
    ]
