# Generated by Django 2.2.7 on 2021-12-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainauguracao',
            name='data_inauguracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da inauguração'),
        ),
        migrations.AlterField(
            model_name='circuitodados',
            name='circuito',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='circuitodados',
            name='cod_filial',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='circuitodados',
            name='faixa_ip',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='circuitodados',
            name='nome_filial',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='circuitodados',
            name='produto',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='circuitodados',
            name='roteador',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='circuitodados',
            name='velocidade',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='circuitovoz',
            name='designacao',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='circuitovoz',
            name='op_urla',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='circuitovoz',
            name='operadora',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='circuitovoz',
            name='regiao_filial',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='circuitovoz',
            name='servico_equipamento',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='circuitovoz',
            name='tel_abrir_chamado',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
