# Generated by Django 2.2.7 on 2020-01-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200114_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDataInauguracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_filial', models.IntegerField()),
                ('loja', models.CharField(max_length=20)),
                ('inauguracao', models.IntegerField()),
            ],
        ),
    ]
