# Generated by Django 2.2.7 on 2021-10-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211021_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainauguracao',
            name='data_inauguracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da inauguração'),
        ),
        migrations.AlterField(
            model_name='circuitodados',
            name='circuito',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='circuitodados',
            name='cod_filial',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='circuitodados',
            name='faixa_ip',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='circuitodados',
            name='nome_filial',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='circuitodados',
            name='produto',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='circuitodados',
            name='roteador',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='circuitodados',
            name='velocidade',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
