# Generated by Django 2.2.7 on 2020-01-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200114_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitodados',
            name='cod_filial',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='circuitodados',
            name='faixa_ip',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
