# Generated by Django 2.2.7 on 2020-01-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200114_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitovoz',
            name='op_urla',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='circuitovoz',
            name='servico_equipamento',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='circuitovoz',
            name='tel_abrir_chamado',
            field=models.IntegerField(null=True),
        ),
    ]
