# Generated by Django 2.2.7 on 2020-01-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200114_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitovoz',
            name='tel_abrir_chamado',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
