# Generated by Django 2.2.7 on 2020-01-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('base', '0009_centraltelefonica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centraltelefonica',
            name='dt_ult_preventiva',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='HistoricoIncidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidente', models.CharField(max_length=400)),
                ('data', models.DateTimeField()),
                ('filial', models.ForeignKey(on_delete='CASCADE', to='core.Lojas')),
            ],
        ),
    ]
