# Generated by Django 2.2.7 on 2020-02-27 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioBh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_nota', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número nota')),
                ('num_ficha_transf', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número ficha de transferência')),
                ('recebido', models.BooleanField(default=False, verbose_name='Recebido')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('filial_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lojas')),
                ('filial_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origem', to='core.Lojas')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.EnvioBh')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recebimento',
                'verbose_name_plural': 'Recebimentos',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
