# Generated by Django 2.2.7 on 2020-02-27 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao_Mensal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_entrega', models.CharField(max_length=30, verbose_name='Mes da entrega')),
                ('conta', models.IntegerField(blank=True, null=True, verbose_name='Conta')),
                ('descricao', models.TextField(max_length=400, null=True, verbose_name='Descricao')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('nf', models.IntegerField(verbose_name='Nota Fiscal')),
                ('ordem', models.IntegerField(verbose_name='Num Ordem')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('status', models.CharField(choices=[('CORRETIVA', 'CORRETIVA'), ('PREVENTIVA', 'PREVENTIVA'), ('MAU USO', 'MAU USO')], max_length=20, verbose_name='Status')),
                ('dt_aquisicao_equipamento', models.DateField(blank=True, null=True, verbose_name='Data Aquisicao')),
                ('dt_ultima_manutencao', models.DateField(blank=True, null=True, verbose_name='Data Ultima Manutencao')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lojas')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fornecedor')),
            ],
            options={
                'verbose_name': 'Manutencao Mensal',
                'verbose_name_plural': 'Manutencoes Mensais',
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pedido', models.IntegerField(blank=True, null=True, verbose_name='Numero pedido')),
                ('dt_vencimento', models.DateField(blank=True, null=True, verbose_name='Data Vencimento')),
                ('obs', models.CharField(blank=True, max_length=455, null=True, verbose_name='Observações')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Equipamento')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lojas')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fornecedor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
