# Generated by Django 2.2.7 on 2021-05-19 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20210510_2223'),
        ('chamado', '0002_auto_20210513_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.Equipamento'),
        ),
    ]
