# Generated by Django 2.2.7 on 2021-05-19 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20200617_1330'),
        ('chamado', '0002_auto_20210518_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.Equipamento'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='defeito',
            field=models.TextField(blank=True, null=True, verbose_name='Defeito'),
        ),
    ]
