# Generated by Django 2.2.7 on 2023-04-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0003_auto_20210518_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='chamado',
            field=models.CharField(max_length=60, verbose_name='Número chamado'),
        ),
    ]
