# Generated by Django 2.2.7 on 2021-05-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0003_chamado_equipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='defeito',
            field=models.TextField(blank=True, null=True, verbose_name='Defeito'),
        ),
    ]
