# Generated by Django 2.2.7 on 2020-01-14 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número da unidade')),
                ('razao_social', models.CharField(max_length=70, verbose_name='Razão Social')),
                ('cnpj', models.IntegerField(verbose_name='CNPJ')),
                ('rua', models.CharField(max_length=50, verbose_name='Rua')),
                ('num_rua', models.IntegerField(verbose_name='Num')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cep', models.IntegerField(verbose_name='cep')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Lojas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('rua', models.CharField(max_length=50, verbose_name='Rua')),
                ('num_rua', models.IntegerField(verbose_name='Num')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cep', models.CharField(max_length=20, verbose_name='cep')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.CharField(choices=[('MONTES CLAROS', 'MONTES CLAROS'), ('BH', 'BH'), ('GERAL', 'GERAL')], default='BH', max_length=20, verbose_name='Area de atuacao'))
            ],
        ),
    ]
