# Generated by Django 2.2.7 on 2021-05-11 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojas',
            name='polo',
            field=models.CharField(choices=[('MONTES CLAROS', 'MONTES CLAROS'), ('BH', 'BH'), ('GERAL', 'GERAL')], default='BH', max_length=20, verbose_name='Polo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='filiais',
            field=models.ManyToManyField(blank=True, to='core.Lojas'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
