# Generated by Django 2.2.7 on 2020-01-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grupo',
            field=models.CharField(choices=[('MONTES CLAROS', 'MONTES CLAROS'), ('BH', 'BH')], default='BH', max_length=20, verbose_name='Area de atuacao'),
        ),
    ]
