# Generated by Django 2.2.7 on 2021-05-18 13:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210511_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_novos_atendimentos', models.BooleanField(blank=True, default=True, verbose_name='Envia e-mail de novos atendimentos ?')),
                ('send_novos_chamados', models.BooleanField(blank=True, default=True, verbose_name='Envia e-mail de novos chamados ?')),
                ('send_notas_presas', models.BooleanField(blank=True, default=True, verbose_name='Envia e-mail de notas presas ?')),
                ('notas_presas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None)),
                ('send_chamados_mensais', models.BooleanField(blank=True, default=True, verbose_name='Envia e-mail de notas presas ?')),
                ('chamados_mensais', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None)),
                ('send_atendimentos_mensais', models.BooleanField(blank=True, default=True, verbose_name='Envia e-mail de notas presas ?')),
                ('atendimentos_mensais', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None)),
            ],
            options={
                'verbose_name': 'Configuração de e-mail',
                'verbose_name_plural': 'Configurações de e-mails',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSocin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default='', max_length=128, verbose_name='Usuário do banco')),
                ('password', models.CharField(blank=True, default='', max_length=128, verbose_name='Senha')),
                ('database', models.CharField(blank=True, default='', max_length=128, verbose_name='Nome do banco')),
                ('host', models.CharField(blank=True, default='', max_length=128, verbose_name='Host/IP do servidor')),
                ('quantidade_para_ativar_envio', models.IntegerField(default=500, verbose_name='Quantidade de notas presas para ativar envio de e-mail')),
                ('ultimo_envio_email_massa', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo envio em massa de e-mails alerta')),
                ('intervalo_entre_envios', models.IntegerField(blank=True, default=30, verbose_name='Intervalo em minutos a considerar para reenviar e-mails em massa')),
            ],
            options={
                'verbose_name': 'Configuração banco Socin',
                'verbose_name_plural': 'Configuração banco Socin',
            },
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='garantia',
            field=models.IntegerField(default=90, verbose_name='Dias de garantia'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cargo',
            field=models.CharField(blank=True, choices=[('gerencia_ti', 'Gerência TI'), ('tecnico', 'Técnico')], max_length=20, null=True, verbose_name='Cargo'),
        ),
    ]
