# Generated by Django 2.2.7 on 2021-05-17 03:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fornecedor_garantia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_notas_presas', models.BooleanField(blank=True, default=True, verbose_name='Envia e-mail de notas presas ?')),
                ('notas_presas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None)),
                ('send_chamados_mensais', models.BooleanField(blank=True, default=True, verbose_name='Envia e-mail de notas presas ?')),
                ('chamados_mensais', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None)),
                ('send_atendimentos_mensais', models.BooleanField(blank=True, default=True, verbose_name='Envia e-mail de notas presas ?')),
                ('atendimentos_mensais', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None)),
            ],
            options={
                'verbose_name': 'Configuração de e-mail',
                'verbose_name_plural': 'Configurações de e-mails',
            },
        ),
    ]
