# Generated by Django 2.2.7 on 2021-12-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210518_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasSocin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0, verbose_name='Quantidade de notas presas')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Notas presas',
                'verbose_name_plural': 'Notas presas',
            },
        ),
    ]
