# Generated by Django 2.2.7 on 2021-05-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_configuracaoemail_send_novos_atendimentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoemail',
            name='send_novos_chamados',
            field=models.BooleanField(blank=True, default=True, verbose_name='Envia e-mail de novos chamados ?'),
        ),
    ]
