# Generated by Django 2.2.7 on 2021-05-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_configuracaoemail_send_novos_chamados'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSocin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default=True, max_length=128, verbose_name='Usuário do banco')),
                ('password', models.CharField(blank=True, default=True, max_length=128, verbose_name='Senha')),
                ('database', models.CharField(blank=True, default=True, max_length=128, verbose_name='Nome do banco')),
                ('host', models.CharField(blank=True, default=True, max_length=128, verbose_name='Host/IP do servidor')),
                ('quantidade_para_ativar_envio', models.IntegerField(default=500, verbose_name='Quantidade de notas presas para ativar envio de e-mail')),
                ('ultimo_envio_email_massa', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo envio em massa de e-mails alerta')),
                ('intervalo_entre_envios', models.IntegerField(verbose_name='Intervalo em minutos a considerar para reenviar e-mails em massa')),
            ],
            options={
                'verbose_name': 'Configuração banco Socin',
                'verbose_name_plural': 'Configuração banco Socin',
            },
        ),
    ]
