# Generated by Django 2.2.7 on 2021-05-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_configuracaosocin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosocin',
            name='database',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Nome do banco'),
        ),
        migrations.AlterField(
            model_name='configuracaosocin',
            name='host',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Host/IP do servidor'),
        ),
        migrations.AlterField(
            model_name='configuracaosocin',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='configuracaosocin',
            name='user',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Usuário do banco'),
        ),
    ]
