# Generated by Django 2.2.7 on 2021-05-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210517_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosocin',
            name='intervalo_entre_envios',
            field=models.IntegerField(blank=True, default=30, verbose_name='Intervalo em minutos a considerar para reenviar e-mails em massa'),
        ),
    ]
