# Generated by Django 2.2.7 on 2021-05-11 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resonsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='setor_visualiza_solucao',
            field=models.BooleanField(default=False, verbose_name='Setores podem ver soluçao'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='setor',
            field=models.CharField(choices=[('FRENTE CAIXA', 'Frente de caixa'), ('RECEPCAO', 'Recepção'), ('SALAO', 'Salao'), ('PERECIVEIS', 'Perecíveis'), ('GERENCIA', 'Gerência'), ('TESOURARIA', 'Tesouraria'), ('SEGURANCA', 'Segurança'), ('RM', 'Rm'), ('RM FISCAL', 'Rm Fiscal'), ('CONTABILIDADE', 'Contabilidade'), ('RH', 'Rh'), ('ACOUGUE', 'Açougue'), ('TREINAMENTO', 'Treinamento'), ('SOE', 'Soe'), ('ALMOXARIFADO', 'Almoxarifado'), ('CPD', 'CPD'), ('CALLCENTER', 'Callcenter'), ('COMERCIAL', 'Comercial'), ('PRECIFICACAO', 'Precificação'), ('PADARIA', 'Padaria'), ('MANUTENCAO', 'Manutenção'), ('HORTIFRUTI', 'Hortifruti'), ('CREDITO', 'Crédito'), ('ENCARREGADOS', 'Encarregados'), ('ALMOXARIFADO', 'Almoxarifado'), ('RESTAURANTE', 'Restaurante'), ('SND', 'SND'), ('GERAL', 'Geral'), ('POSTO-PISTA', 'Posto-Pista'), ('POSTO-ADM', 'Posto-Adm'), ('LOGISTICA', 'Logistica'), ('EXPEDICAO', 'Expedição'), ('PRESIDENCIA', 'Presidência')], max_length=50, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('p', 'PENDENTE'), ('r', 'RESOLVIDO'), ('o', 'CANCELADO')], default='p', max_length=1),
        ),
    ]
