# Generated by Django 2.2.7 on 2020-06-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_auto_20200617_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('p', 'PENDENTE'), ('r', 'RESOLVIDO'), ('o', 'CANCELADO')], default='p', max_length=1),
        ),
    ]
