# Generated by Django 2.2.7 on 2021-12-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0006_auto_20211211_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='problema',
            field=models.CharField(max_length=1024, verbose_name='Problema'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='solucao',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Resolução'),
        ),
    ]
